version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: vecai
    main: ./cmd/vecai
    binary: vecai
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: vecai
    ids:
      - vecai
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: abdul-hamid-achik
    name: vecai
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

homebrew_casks:
  - name: vecai
    repository:
      owner: abdul-hamid-achik
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/abdul-hamid-achik/vecai"
    description: "AI-powered codebase assistant with semantic search and Claude intelligence"
    license: "MIT"
    install: |
      bin.install "vecai"
    test: |
      system "#{bin}/vecai", "version"
    skip_upload: "{{ if .Env.HOMEBREW_TAP_TOKEN }}false{{ else }}true{{ end }}"
